pipeline {
        agent any 
    environment {
        IMAGE_NAME = 'samdatta93/internal-project-cp'
        DOCKERHUB_CREDS = 'dockerhub-creds'
        VERSION = "0.0.${env.BUILD_NUMBER}"
                AWS_REGION = 'us-east-1'
                CLUSTER_NAME = 'sd-cluster'
HOME = '/tmp'
KUBECONFIG = '/tmp/.kube/config'
    }

    stages {
        stage('Git Checkout') {
            steps {
                                echo 'Retrieve source from github' 
                sh """
                whoami
                pwd
                """
                checkout scm
            }
        }

        stage('Install Dependencies') {
                        agent {
                docker { 
                    image 'node:14-alpine'
                    args '-e HOME=/tmp -e NPM_CONFIG_PREFIX=/tmp/.npm'
                    reuseNode true
                }
            }
            steps {
                                echo 'Run npm install' 
                sh 'npm ci'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                                        echo 'build the image' 
                    sh "docker build -t ${IMAGE_NAME}:${VERSION} ."
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: "${DOCKERHUB_CREDS}",
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASSWORD'
                )]) {
                    sh """
                                                echo 'push the image to docker hub' 
                        echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USER}" --password-stdin
                        docker push ${IMAGE_NAME}:${VERSION}
                    """
                }
            }
        }

                stage('Remove local docker image') {
            steps{
                                sh "echo 'remove local docker image'"
                sh "docker rmi ${IMAGE_NAME}:${VERSION}"
                //sh "docker rmi $imageName:$BUILD_NUMBER"
            }
        }

                stage ('Deploy to EKS') {
        /*      when {
                        branch 'main'
                        }
        */
                  agent {
                docker { 
                    image 'samdatta93/aws-cli-kubectl-cp:latest'
                    args '--entrypoint="" --network host'
                }
            }
                        steps {
/*echo 'Started deploying'
                sh """
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.31.2/2024-11-15/bin/linux/amd64/kubectl
chmod +x ./kubectl
mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
*/
withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']]){
sh '''

mkdir -p $(dirname $KUBECONFIG)
aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME --kubeconfig $KUBECONFIG
pwd
kubectl apply -f k8s/deployment.yaml --kubeconfig=$KUBECONFIG
kubectl apply -f k8s/service.yaml --kubeconfig=$KUBECONFIG
kubectl get svc
                '''
                echo 'Deployed to EKS' 
}
                
            }
                }
    }

    post {
        always {
            cleanWs()
        }
    }
}
