apiVersion: v1
kind: Service
metadata:
  labels:
    app: external-app-svc
  name: external-app-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: external-app
    ver: v1.0
  type: LoadBalancer
